version: '3.7'

services:
  mysql:
    container_name: biblioteca-mysql
    image: biblioteca-mysql2
    build:
      context: .
      dockerfile: ./dockerfile.mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      # schema
    networks:
      - biblioteca-network
    ports:
      - 3306:3306
  app:
    depends_on:
      - mysql
    container_name: biblioteca-app
    image: biblioteca-app2
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    networks:
      - biblioteca-network

networks:
  biblioteca-network: